AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This CloudFormation template creates a role assumed by CloudFormation
  during CRUDL operations to mutate resources on behalf of the customer.

Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      MaxSessionDuration: 8400
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: resources.cloudformation.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              StringLike:
                aws:SourceArn:
                  Fn::Sub: arn:${AWS::Partition}:cloudformation:${AWS::Region}:${AWS::AccountId}:type/resource/AWS-QBusiness-Application/*
      Path: "/"
      Policies:
        - PolicyName: ResourceTypePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "iam:GetSAMLProvider"
                - "iam:PassRole"
                - "kms:CreateGrant"
                - "kms:DescribeKey"
                - "kms:RetireGrant"
                - "qbusiness:CreateApplication"
                - "qbusiness:DeleteApplication"
                - "qbusiness:GetApplication"
                - "qbusiness:ListApplications"
                - "qbusiness:ListTagsForResource"
                - "qbusiness:TagResource"
                - "qbusiness:UntagResource"
                - "qbusiness:UpdateApplication"
                - "sso:CreateApplication"
                - "sso:DeleteApplication"
                - "sso:DescribeInstance"
                - "sso:PutApplicationAccessScope"
                - "sso:PutApplicationAuthenticationMethod"
                - "sso:PutApplicationGrant"
                Resource: "*"
Outputs:
  ExecutionRoleArn:
    Value:
      Fn::GetAtt: ExecutionRole.Arn
